In [1]:
from numpy import *

In [6]:
a = array([[1,2,3],[4,5,6],[7,8,9]])

In [12]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
roll(a,1,axis=1)

array([[3, 1, 2],
       [6, 4, 5],
       [9, 7, 8]])

In [15]:
roll(a,1,axis=0)

array([[7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]])

In [19]:

for i in range(3):
    for j in range(3):
        kq=roll(roll(a,i,axis=0),j,axis=1)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3 1 2]
 [6 4 5]
 [9 7 8]]
[[2 3 1]
 [5 6 4]
 [8 9 7]]
[[7 8 9]
 [1 2 3]
 [4 5 6]]
[[9 7 8]
 [3 1 2]
 [6 4 5]]
[[8 9 7]
 [2 3 1]
 [5 6 4]]
[[4 5 6]
 [7 8 9]
 [1 2 3]]
[[6 4 5]
 [9 7 8]
 [3 1 2]]
[[5 6 4]
 [8 9 7]
 [2 3 1]]
